### ISSUE TITLE
External issues that need community support

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#109]
- [ ] Adding tag on BODY tag - https://github.com/meteor/meteor/issues/2561
- [ ] Language attributes to templates - https://github.com/meteor/meteor/issues/3400
- [ ] Make Meteor's build process handle few plugins on one file extension, so we can run ng-annotate on .js files - https://github.com/MeteorCommunity/discussions/issues/51
- [ ] Official Meteor support for bower with handling conflicts - https://github.com/mquandalle/meteor-bower/issues/30
- [ ] Ability to change Blaze's default-delimiters - https://github.com/meteor/meteor/issues/2765
- [ ] Ability to extend Meteor's command line to do something like Yeoman's angular with meteor: "meteor create --angular socially" - https://github.com/MeteorCommunity/discussions/issues/9

**Comment by Urigo** [comment]
Closing as I've discussed it all with the Meteor team and @netanelgilad wrote a great pull request for solving the most relevant issue.
