### ISSUE TITLE
Cleanups before releasing 1.3.6

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1207]
- [x] Document all scenarios of helpers - https://github.com/Urigo/angular-meteor/issues/955#issuecomment-168457682
- [x] https://github.com/Urigo/angular-meteor/issues/1105
- [x] https://github.com/Urigo/angular-meteor/issues/1108
- [x] Make sure this is documented - https://github.com/Urigo/angular-meteor/issues/1088
- [x] Make sure this is working - https://github.com/Urigo/angular-meteor/issues/1034#issuecomment-168489648
- [x] Make sure this scenario is documented and handled - https://github.com/Urigo/angular-meteor/issues/1064#issuecomment-172565389
- [x] https://forums.meteor.com/t/angular-meteor-cant-access-helper-properties-angular-1/16176
- [x] https://forums.meteor.com/t/does-dburles-collection-helpers-work-with-angular-meteor/12800/4
