### ISSUE TITLE
Test Coverage in angular-meteor

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#367]
Hi!  now that we have tests in angular-meteor, we would love your help in adding as many tests as possible.
We will add unit tests as well as integration tests.
You can add integration scenarios in the 'examples' folder as a complete project with tests.

We will add tests scenarios here and you can create your own:

#### Save

- [ ] autobind
- [ ] autobind - nested ng-repeat
- [ ] autobind - nested ng-repeat - ng-model on nested
- [ ] autobind - pushing item without permission
- [ ] Save function - new object
- [ ] Save function - updated object
- [ ] Save function - updated deep nested object
- [ ] Save function - empty
- [ ] Remove function - existing object
- [ ] Remove function - parameter id
- [ ] Remove function - not existent object
- [ ] Remove function - empty, remove all
- [ ] Handle Mongo ID and Meteor Object ID - related to #1 , https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L38  
- [ ] Handle insert/remove/update documents from the command line - related to #73 
- [ ] Transform functions - related to #185 #195 
- [ ] Collection Hooks
- [ ] Collection Helpers - #276  https://github.com/dburles/meteor-collection-helpers
- [ ] CollectionFS with Collection
- [ ] CollectionFS with Object
- [ ] test the options parameter

#### Save

- [ ] Everything in $meteorCollection
- [ ] Save object with nested ng-repeat sub documents
- [ ] test the options parameter

- [ ] Handle Mongo ID and Meteor Object ID - related to https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L38 #1 

## getReactively
- [ ] Nested object change - related to #184 
## meteor-include
- [ ] Include regular Blaze template inside .ng.html
- [ ] Include loginButtons

## General
- [ ] Load Angular app without JQuery loads Angular's JQuery Lite
- [ ] Load Angular app with JQuery loads JQuery before Angular - related to #2 
- [ ] Controller as vm syntax
- [ ] Template compilation #229 #235 #255 

## Performance
- [ ] Initial subscribe
- [ ] #208

**Comment by dagatsoin** [comment]
Hello Urigo,

I would love to help on this because:
1) I am looking for a while for a project to begin in the "test world". I have never done this.
2) I am actually working on an meteor-anagular project so I think I got the time to get in.

Have you got an introduction to test ? I am completely new in this, there is a lot of docs on tests but I prefer a doc you could recommend me to begin on the same bases as you.

**Comment by Urigo** [comment]
@dagatsoin that will be awesome!
we already started with integration tests so you can see some examples here:
https://github.com/Urigo/angular-meteor/tree/master/tests/integration

about unit tests, you can use Jasmine as if it was a regular Angular application, same thing with E2E with Protractor

**Comment by ccortezia** [comment]
Is this checklist up-to-date ?

**Comment by Urigo** [comment]
not really, will update tomorrow, thanks for the catch

**Comment by Urigo** [comment]
thanks everyone for all the help, our current state is much better!
